apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- ./todo-broadcaster/manifests/configMap.yaml
patches:
- path: ./manifests/gateway.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: 4.10-a152ebef2de245a4d099e905ae17d29ef23fad95
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: 4.10-a152ebef2de245a4d099e905ae17d29ef23fad95
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: 4.10-a152ebef2de245a4d099e905ae17d29ef23fad95
