apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- ./todo-broadcaster/manifests/configMap.yaml
patches:
- path: ./manifests/gateway.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-24b119505023f167b80e758fd228114c256039f4
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-24b119505023f167b80e758fd228114c256039f4
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-24b119505023f167b80e758fd228114c256039f4
