name: Deploy application to Cluster 

on:
  push:
    branches: [ main ]
    tags: ['*']

env: 
  BRANCH: ${{ github.ref_name }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy-to-cluster:
    name: Deploy the application to the cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main 
          fetch-depth: 0

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      
      - name: 'Use the right image in staging'
        run: |
          cd project/overlays/staging
          kustomize edit set image lucksei/todo-app=lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-backend=lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-broadcaster=lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}

      - name: 'Use the right image in production'
        if: ${{ github.ref_type == 'tag'}}
        run: |
          cd project/overlays/production
          kustomize edit set image lucksei/todo-app=lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-backend=lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-broadcaster=lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'project/overlays/*/kustomization.yaml'
          message: New version released ${{ github.sha }}
          pull: '--rebase --autostash origin ${{ env.BRANCH }}'